version : "1"
services:
  kyc-backend:
    build: ./KYC backend
    container_name: kyc-backend
    environment:
      - PORT=3004
      - NODE_OPTIONS="--experimental-specifier-resolution=node"
    ports:
      - 3434:33434

  express-backend:
    build: ./express-backend
    container_name: backend
    environment:
      - PORT=3002
      - NODE_OPTIONS="--experimental-specifier-resolution=node"
    ports:
      - 3433:33433

  react-frontend:
    build: ./react-frontend
    container_name: frontend
    ports:
      - 33435:80
