version : "1"
services:
  kyc-backend:
    build: ./KYC backend
    container_name: kyc-backend
    environment:
      - PORT=3004
      - NODE_OPTIONS="--experimental-specifier-resolution=node"
    ports:
      - 3004:3004

  express-backend:
    build: ./express-backend
    container_name: backend
    environment:
      - PORT=3002
      - NODE_OPTIONS="--experimental-specifier-resolution=node"
    ports:
      - 3002:3002

  react-frontend:
    build: ./react-frontend
    container_name: frontend
    ports:
      - 3000:80
